plugins {
	id 'maven-publish'
	alias libs.plugins.quilt.loom
}

version = "$project.version+${libs.versions.minecraft.get()}"

loom {
	mods {
		'golemancy' {
			sourceSet('main')
		}
	}
}

repositories {
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases/'
    }
	maven {
		name = 'Shedaniel'
		url = 'https://maven.shedaniel.me/'
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/releases/'
	}
}


dependencies {
	minecraft libs.minecraft
	mappings variantOf(libs.quilt.mappings) { classifier 'intermediary-v2' }
	modImplementation libs.quilt.loader

	modImplementation libs.quilted.fabric.api
	modImplementation(include(libs.cca.base.get())) {
		exclude group: 'net.fabricmc.fabric-api'
	}
	modImplementation(include(libs.cca.entity.get())) {
		exclude group: 'net.fabricmc.fabric-api'
	}

	modImplementation(libs.modmenu) {
		exclude group: 'net.fabricmc.fabric-api'
	}
	modImplementation(libs.cloth.config) {
		exclude group: 'net.fabricmc.fabric-api'
	}
}

processResources {
	def version = project.version
	def group = project.group
	inputs.properties 'version': version, 'group': group

	filesMatching('quilt.mod.json') {
		expand 'version': version, 'group': group
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = 17
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17

	withSourcesJar()
}

// If you plan to use a different file for the license, don't forget to change the file name here!
jar {
	def projectName = project.name
	inputs.property 'projectName', projectName

	from('LICENSE') {
		rename { "${it}_$projectName" }
	}
}

// Configure the maven publication
publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
