[versions]
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.23"

quilt_loom = "1.15.+"
quilt_loader = "0.28.1"

quilted_fabric_api = "7.6.0+0.92.2-1.20.1"
cca = "5.2.3"
cloth_config = "11.1.136"
modmenu = "7.2.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

cca_base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca_entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
cloth_config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth_config" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }